// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include <stdio.h>

// Include the trusted helloworld header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the helloworld.edl file.
#include "helloworld_t.h"
#include "hello.pb.h"
ssize_t read(int fd, void *buf, size_t count)
    {
        printf("***************read called\n");
        return 0;
    }

    off_t lseek(int fd, off_t offset, int whence)
    {
        printf("***************lseek called\n");
        return 0;
    }

    ssize_t write(int fd, const void *buf, size_t count)
    {
        printf("***************wrie called\n");
        return 0;
    }
int ecall_run(const char *input,
    uint64_t input_len,
    char **output,
    uint64_t max_len,
    uint64_t *output_len)
{


    hello_world::HelloOutput enclave_output;
    hello_world::HelloInput enclave_input;
    std::string str("Hello");

    printf("In Enclave");
    if (!enclave_input.ParseFromArray(input, input_len)) {
        printf("Could not parse input from array\n");
        return 1;
    }
    str = str + " " + enclave_input.to_greet();

    enclave_output.set_greeting_message(str);
    *output = (char*)oe_host_malloc(max_len);
    if (!enclave_output.SerializeToArray(*output, enclave_output.ByteSize()))
    {
        return 1;
    }
    *output_len = enclave_output.ByteSize();

    return 0;
}
